name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: bharathr89/test-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
